### ISSUE TITLE
Show desktop icon

### ISSUE THREAD

**Issue by ocafebabe** [OrancheloTeam/oranchelo-icon-theme#3]
Hey,

I really like your theme but I do have a small issue with it: the "Show desktop" icon doesn't show up correctly!

If you look at the 2 provided screenshots you'll see what I'm talking about:

1) The icon is not shown

![screenshot-1](https://cloud.githubusercontent.com/assets/3409735/13466797/8c1b74f8-e069-11e5-9b3a-542b24137894.png)

2) The icon is shown on mouse over but the color is weird

![screenshot-2](https://cloud.githubusercontent.com/assets/3409735/13466802/926cdb9e-e069-11e5-8d4a-48de09bfd188.png)

Do you have any idea what could be causing this?

BTW I'm on Linux Mint 17.3...

Thanks

**Comment by Madh93** [comment]
Hi, thank you for post your problem.

The reason about this problem is the [icon](https://github.com/Madh93/oranchelo-icon-theme/blob/master/Oranchelo/places/symbolic/user-desktop.svg) and your panel ("cinnamon" desktop theme) use the same color [#555555](http://www.color-hex.com/color/555555). The icon is shown on mouse over because hover color is different.

Solution? Two posible ways:

- Change color of panel theme

Or if you prefer i can:

- Tell this problem to [ZayronXIO](http://zayronxio.deviantart.com/) to edit icon color.

**Comment by ocafebabe** [comment]
I would prefer not to change the color of the panel since it's the default Cinnamon theme and I like it that way... But I understand that changing the color of the icon might not please other users of this theme... 

Don't bother if this is too much trouble!

Thanks

**Comment by Madh93** [comment]
I tell him about this and i will notify you :wink:

**Comment by ocafebabe** [comment]
Cool thanks :+1:

**Comment by Madh93** [comment]
Sorry for the delay. `show-desktop` icon was changed [v0.7.3](cc7133d6ef2928f0760a9b6cff73af3b41bfb608) 😉
